```{r}
dados = read.csv("tempo.csv", sep = ";", na.strings = "", stringsAsFactors = T)
summary(dados)
head(dados)
```
Explorar dados categóricos - Aparencia
```{r}
counts = table(dados$Aparencia)
barplot(counts, main = "Aparencia", xlab = "Aparencia")
#Resultado: 1 resultado chamado "menos"
```
Explorar dados categóricos - vento
```{r}
counts = table(dados$Vento)
barplot(counts, main = "Vento", xlab = "Vento")
#Resultado: Tudo ok
```
Explorar dados numéricos - Temperatura
```{r}
summary(dados$Temperatura)
hist(dados$Temperatura)
boxplot(dados$Temperatura)
#Resultado: 1 dado outlier
```
Explorar dados numéricos - Umidade
```{r}
summary(dados$Umidade)
hist(dados$Umidade)
boxplot(dados$Umidade)
#Resultado: 1 dado NA, 1 outlier
```
Verificar valores faltantes
```{r}
dados[!complete.cases(dados),]
#Resultado: Falta 1 dado em Umidade e 1 em vento
```
substituir valores faltantes e retirar outliers
```{r}
#Umidade - valores NA
summary(dados$Umidade)
median(dados$Umidade, na.rm = T)
dados[is.na(dados$Umidade),]$Umidade = median(dados$Umidade, na.rm = T)
dados[!complete.cases(dados),]
#Umidade - outliers e fora de dominio
boxplot(dados$Umidade)
dados[dados$Umidade > 100, ]$Umidade = median(dados$Umidade, na.rm = T)
boxplot(dados$Umidade)
#temperatura - outliers e fora de dominio
boxplot(dados$Temperatura)
dados[dados$Temperatura > 130, ]
median(dados$Temperatura)
dados[dados$Temperatura > 130, ]$Temperatura = median(dados$Temperatura)
```
substituir valores faltantes e escritos errados nas variaveis categoricas
```{r}
#Vento - valores NA
unique(dados$Vento)
summary(dados$Vento)
dados[is.na(dados$Vento), ]$Vento = "FALSO"
#Aparencia - dados errados
unique(dados$Aparencia)
summary(dados$Aparencia)
dados[dados$Aparencia == "menos", ]$Aparencia = "sol"
dados$Aparencia = factor(dados$Aparencia)
```
Conferir tabela final
```{r}
dados
```

